# METADATA
title: "{code}bridge"
email: your-email@domain.com
## Description must be 160 characters or less
description: A civic technology lab, based in Cape Town Metro, that brings together programmers, hacktivists, data junkies and journalists to create apps for social change.
baseurl: "/"
url: "http://codebridge.co.za/"

# OPEN GRAPH
## OG Description must be 125 characters or less
og_description: A Cape Town civic tech lab that brings together programmers, hacktivists and journalists to create apps for social good.
og_latitude: -33.976608
og_longitude: 18.46662
twitter_username: "@codebridge"
github_username: codebridge-za
facebook_page: codebridge
## Video ID for video on homepage
ytid: CG6M64bicEg

# NAVIGATION
navigation:
- text: Donate
  url: /donate.htm
- text: Events
  url: /events.htm
- text: Contact
  url: /contact.htm

# BUILD SETTINGS
permalink: /:categories/:year-:month-:day/:title.htm

# EXCLUDE
exclude: [CNAME, Vagrantfile, README.md, /assets/img/originals, /assets/css/style.css, /backup]

#RESOURCES USED
## Use Material Design Colors - https://www.google.com/design/spec/style/color.html
## Membership Pricing Table - http://bootsnipp.com/snippets/z1EBX
## Email address encoder - http://www.the-art-of-web.com/javascript/mailto/
## Font pairing - https://femmebot.github.io/google-type/
## Free Stock Images - https://unsplash.com/
## 7zip Extrator - http://www.kekaosx.com/en/ (OSX) or http://www.7-zip.org/ (WINDOWS)